server:
  port: 8088
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/jiaxueqing/config-repo.git
          search-paths: config-repo
          username: 1
          password: 1